spring:
  application:
    name: name-service
  cloud:
    consul:
        host: localhost
        port: 8500
        discovery:
           instanceId: ${spring.application.name}:${random.value}
           healthCheckInterval: 20s
name: dasun samarasiri